#!/usr/bin/env python
# -*- coding: utf-8 -*-
 
 
 
import os
 
os.system("apt-get install figlet")
os.system("apt-get install aircrack-ng")
os.system("clear")
os.system("figlet HANSHAKE CRACKER")
 
print("""
Handshake Cracker By EnesDuran
 
Please Enter a File or Directory
 
""")
 
process = True
 
while process:
    print("")	
    processno = input("# $: ")
    if processno == "":
        print("No such file or directory. Please enter a valid directory ! ")
        print("")
    else:
        process = False
       
        print("")
        print("Enter your wordlist .txt file or directory")
        wl = input("# $:")
       
 
os.system("aircrack-ng " + processno + " -w " + wl)
